version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
#    volumes:
#      - postgres:/data/postgres
    ports:
      - "5432:5432"
#volumes:
#  postgres: